### ISSUE TITLE
no README.md!!11!!11

### ISSUE THREAD

**Issue by QAEZZ** [YendisFish/Efi.Net#1]
AS A SUPERIOR LINUX USER (ubuntu btw), AND AN AVID ADVOCATE THAT ADVOCATES FOR THE ADVOCATION OF ADVOCATING FOR OPEN SOURCE SOFTWARE, I AM EXTREMELY ANGRY WITH YOU.!!!1!!1 😡😡😒😡😠.

YOU DO NOT HAVE A README.MD EXPLAINING THE USAGE AND REASON FOR THIS REPOSITORY!!11!!1
NOR DO YOU HAVE A LICENSE!!11!

FIX NOE!!111OW
1!!!111

**Comment by YendisFish** [comment]
here https://github.com/YendisFish/Efi.Net/blob/main/README.md

**Comment by QAEZZ** [comment]
so based that you linked the site
